all:get-one-file-sig client-shell.c
	gcc -w client-shell.c -o client-shell

get-one-file-sig:get-one-file-sig.c
	gcc -w get-one-file-sig.c -o get-one-file-sig

clean:
	rm -f client-shell get-one-file-sig *~